[package]
name = "sident"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
chrono = "0.4.41"
log = "0.4.27"
num_enum = "0.7.4"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["time", "io-util"] }
tokio-serial = "5.4.5"
